vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        media_object:
            uri_prefix: /media/images
            upload_destination: '%kernel.project_dir%/public/media'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
