version: '3.8'

services:

  phpstan:
    build: images/phpstan
    image: flo-phpstan:develop
    volumes:
      - "${ROOT_PATH}:/app"
    working_dir: /app/application/backend

  phpqa:
    build: images/phpqa
    image: flo-phpqa:develop
    volumes:
      - "${ROOT_PATH}:/app"
    working_dir: /app/application/backend
