name: Analyse frontend

on:
  pull_request:
    paths:
      - application/web/**/*.ts
      - application/web/**/*.vue
      - .github/workflows/analyse_backend.yml

jobs:
  analyse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Prepare
        run: |
          cd application/web
          npm install

      - name: ESLint
        run: |
          cd application/web
          npm run lint
