name: Analyse backend

on:
  pull_request:
    paths:
      - application/backend/**/*.php
      - .github/workflows/analyse_backend.yml

jobs:
  analyse:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.2']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Prepare
        run: |
          cd application/backend
          composer install --no-progress --prefer-dist --optimize-autoloader
          php bin/console cache:warmup --env=dev

      - name: PHPMD
        run: make phpmd

      - name: PHPStan
        run: make phpstan-analyse

      - name: ECS check
        run: make ecs-check
