name: Analyse frontend

on: [pull_request]

jobs:
  analyse:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Prepare
        run: |
          cd application/web
          npm install

      - name: ESLint
        run: |
          cd application/web
          npm run lint
