name: Analyse backend

on: [pull_request]

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare analysis
        run: |
          cd application/backend
          composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
          php bin/console cache:warmup --env=dev
      - name: Test
        run: |
          cd application/backend
          ls -l
          ls -l var/
          ls -l var/cache/
          ls -l var/cache/dev/
          ls -l var/cache/dev/Symfony
      - name: ECS check
        run: make ecs-check
      - name: PHPStan
        run: make phpstan-analyse
