name: Analyse backend

on: [pull_request]

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ECS check
        run: make ecs-check
      - name: PHPStan
        run: make phpstan-analyse
